sailfishos/mkcal

src/CMakeLists.txt
tests/CMakeLists.txt

Adds the `TIMED_SUPPORT` cmake flag which, when set, will in turn pass the `TIMED_SUPPORT` pre-processor define on to the compiler.
Updates the spec file to set the flag by default.
Fixes a regression introduced in d1bf0e9d25ab42e91fe70c8 that prevented alarms from working.

Build with timed-qt5 support

---

src/extendedcalendar.cpp
src/sqlitestorage.cpp

Here are two commits fixing two separated issues :
- since we are now validating notebooks, it has created an issue when calling `ExtendedCalendar::deleteAllIncidences()`. This method is used nowhere except in the webcal plugin, I guess, so it has been unnoticed. This method is calling `Calendar::close()` to clear memory of all incidences and of all tables... But one table that is cleared, is the notebook association one (see `MemoryCalendar::close()`). So it's not possible anymore to call `Calendar::notebook(incidence)` after this, while the code actually deleting the incidence in sqlitestorage.cpp is checking that the incidences belong to a notebook... It is debatable to know if it's better not to kill the notebook association on call of `deleteAllIncidences()`, but it's actually …

Cannot delete or add events under certain conditions

---

CMakeLists.txt
rpm/mkcal-qt5.spec
src/extendedcalendar.cpp
src/extendedcalendar.h
tests/tst_storage.cpp

This has the consequence that it's not mandatory anymore to declare any exception recurrenceId as an exdatetime of the parent. The API of rawExpandedEvents() is modified to simplify it. The inclusion parameters were not used. The expansion time zone has also been removed, so returned start time and end time are always given in the system time zone. This allow to transparently handle the events declared in local time.
@chriadam and @pvuorela, the purpose of this MR is to simplify a lot the rawExpandedEvents() by relying on the upstream OccurrenceIterator. It requires to change the method API though. When looking where it is used, I find only mer-core/nemo-qml-plugin-calendar in calendarworker.cpp. There it is used without the inclusive parameters, so I removed them. It is also used with …

[mkcal] Simplify rawExpandedEvents() by using upstrean OccurrenceIterator.

---

src/sqliteformat.cpp
src/sqlitestorage.cpp
src/sqlitestorage.h
tests/tst_storage.cpp

Maybe some quick cleanups before i proceed with the schema update. Removed unnecessary tail parameters, unnecessary null check and renamed the sqlite wrappers so they don't get confused with the real api and allow in the future to use either one based on which makes more sense.  
Small detail: used NULL on tail parameters instead of nullptr like a couple of lines did as that felt more c-style for sqlite api.
@chriadam @dcaliste

Code cleanups. JB#52853

---

src/sqlitestorage.cpp
src/sqlitestorage.h
tests/tst_storage.cpp

Previous correction for single day events without
end date set in commit b27fc5637452dd3e44d6b81d9a4860348782a608
created a situation where all single day events
starting before the start date in the loading
range were also included.
@pvuorela , working on timing measurements for loading, I notice that all my birthday events were loaded in a range load for current month. This is erroneous : birthdays should be loaded as recurring events and not in a plain range load (except if the range include the day of birth). After searching a bit, I noticed that single day events (without end date) are wrongly loaded because of the `or DateEndDue = 0` in the SQL query. This case (no end date) should take the start date for the end date constraint. That's what the patch is doing. I've updated the …

[mkcal] Correct loading of one day incidence.

---

src/extendedstorage.cpp
src/extendedstorage.h
src/sqlitestorage.cpp

This commit allows to re-open() a closed ExtendedStorage
object, without it complaining on notebook addition failures.
@pvuorela, not a big deal (hopefully, never sure with mKCal), but this is to supress the warning message in the new timing test. It's due to the fact that:
- open()
- do something…
- close()
- open() again
is not working. That's because the notebooks are not cleared from memory on close, and on re-open, they are already existing and cannot be added to the ExtendedStorage.

[mkcal] Make ExtendedStorage clears the notebook references on close.

---

rpm/mkcal-qt5.spec
src/extendedstorage.cpp
tests/CMakeLists.txt
tests/tst_perf.cpp
tests/tst_perf.h

@pvuorela, this is adding a test whose purpose is to display timing for read and write in the database. This would allow to check that we don't create any obvious regression in term of timing when modifying the database code.
When used on #10 for instance, it shows that there is no penalty (or gain) done by moving the statements into the private part of SqliteFormat.
The test is design to work with an ad hoc temporary database, created on the fly with custom properties, recurrences, exceptions and alarms. But in case one want to run it on an existing database, one can use the well-known environment variable `SQLITESTORAGEDB`.
What do you think ?

[mkcal] Add a test measuring saving and loading times.

---

src/sqliteformat.cpp
src/sqlitestorage.cpp
tests/tst_storage.cpp

@pvuorela, trying to fix the broken test (see tst_icalAllDay), I noticed that local time start and stop times were not saved as such, but saved as time zone events within the system time zone.
This is due to the fact that `QDateTime::timeZone()` is returning the system time zone for events with Qt::LocalTime spec. So everything is working as long as one does not change the time zone of the device, where local time events are not floating anymore but pinned to the previous system time zone. The change was easy, not to save the time zone in case of Qt::LocalTime spec. Particularly, this case where the time zone database column is empty was already existing in the reading part, and already properly restoring date time to a local time spec. So far so good.
But doing this created a major issue …

Local time handling

---

src/servicehandler.cpp
src/servicehandler.h
src/sqliteformat.cpp
tests/tst_storage.cpp
tests/tst_storage.h

While working on attendee support in nemo-qml-plugin-calendar, I noticed that it's not convenient to default to the invitation plugin in tests. I'm thus adding a commit here so mKCal can look for plugins in a directory that can be given with an environment variable. Then tests can use this variable to load ad hoc plugins from the test directory without poluting the system directories.
I also noticed that saving the organizer as an attendee was not optimal when the organizer is actually in the attendee list, because his role, status and RSVP were resetted to default values. I've added a test demonstrating the problem and I added a fix in the saving code : if the organizer is in the attendee list, use it's attendee definition instead of creating a new one.
@pvuorela , not in a hurry, when …

Fix an issue with attendee saving and add some more flexibility to service handler

---

src/dummystorage.h
src/extendedcalendar.cpp
src/extendedstorage.cpp
src/extendedstorage.h
src/sqlitestorage.cpp
src/sqlitestorage.h
tests/tst_storage.cpp

@pvuorela, this is another API break :/ I'm sorry. In my opinion these optional arguments from these two methods can be quite detrimental to the API consistency and make the code refactoring difficult by creating several internal different code paths for the same call. In addition, the `onlyMemory` argument from deleteNotebook() is dangerous by leaving orphaned incidences in the database if missused. The `signal` argument from addNotebook was used only during initialisation to avoid too many signaling. This can be achieved by calling the modifyNotebook() directly.
Hopefully this is not breaking any client code… What do you think ?

[mkcal] Remove optional arguments from addNotebook() and deleteNotebook()

---

rpm/mkcal-qt5.spec
src/extendedcalendar.cpp
src/extendedcalendar.h
src/extendedstorage.cpp
src/extendedstorage.h
src/extendedstorageobserver.h
src/sqliteformat.cpp
src/sqliteformat.h
src/sqlitestorage.cpp
src/sqlitestorage.h
tests/tst_storage.cpp
tests/tst_storage.h
tools/mkcaltool/mkcaltool.cpp

The existing storageModified() signal is emitted whenever the ".changed" file is touched. Restrict its emission only if some change has been done to the database content from an external process. Currently emit it also if a change is done in process to any notebook.
Add a new signal storageUpdated() that is emitted on any modification of the database component parts (addition, modification of deletion) to be in part with the associated mCalendar.
The distinction between the two signals is done internally thanks to a counter saved to the DB in a new Metadata table. On every change this counter is incremented in sync with modifications, saved to DB and stored locally in the SqliteStorage private member. In the `fileChanged` signal handler, this counter is reread from DB. If it doesn't match …

[mkcal] Add a new storage observer signal on DB update

---

src/extendedstorage.cpp
src/sqliteformat.cpp
tests/tst_load.cpp
tests/tst_storage.cpp

Remove also the warning when purging an already deleted incidence.
Ensure that incidence exists before deletion in notebook delete function.
@pvuorela, following your remark when merging #19, I'm modifying a bit the `tst_load` to ensure that it can run on an existing DB without default notebook. Doing such created some warnings as mentioned above, so I'm also fixing them. What do you think ?

[mkcal] Correct tst_load to work on existing DB.

---

src/sqliteformat.h
tests/tst_load.cpp

Events defined with RDATE only are otherwise not seen
as recurring and are not loaded in a byDate fetch.
@pvuorela, this is fixing https://forum.sailfishos.org/t/bug-in-calendar-app-alarm-to-calendar-entry-correctly-goes-off-but-calendar-entry-is-not-visible-in-the-calendar/10894 In the ICS of the poster, the event is defined with RDATE, starting in January. The events are not showing in the calendar, because, the incidence is actually loaded only when swiping to January, and then the ranges for the other months are already flagged as loaded in nemo-qml-plugin-calendar, so the occurrences for these ranges are not recomputed.
The fact that we also load components with EXDATE only with the patch, is not a real issue in my opinion. In fact such incidences are recurring by definition so they …

[mkcal] Load rdates-only components as recurring events.

---

src/extendedstorage.cpp

QCOMPARE() was failing on comparing invalid QDateTimes between getLoadDates()
returned and separately created. Avoid timezones on such not to confuse
any comparisons.
@Tomin1 @dcaliste

[mkcal] Fix tst_load unit test failure. JB#57856

---

src/extendedstorage.cpp
tests/tst_storage.cpp
tests/tst_storage.h

@pvuorela, I noticed that cancelled occurrences were not removing their alarm and tried to fix it. Doing so, I understand that the code for recurring events in general was broken regarding the alarms. I've added a test demonstarting all possible failing situations:
- change time of the next occurrence : alarm will ring twice, one time on the normal time and one time for the new time,
- delete the next occurrence : alarm will ring anyway,
- cancel one occurrence, alarm will ring anyway.
That's because the parent does not contains anymore the EXDATE of the exceptions, so the getNextDateTime() in setAlarms() is always returning the next time in the recurrence without taking into account the exceptions. I'm proposing to correct this in the setAlarms() routine by adding the different cases of …

[mkcal] Fix alarms for recurring events with exceptions.

---

src/extendedstorage.cpp

The laterThan was supposed to be moved one second (and
not one day) because nextTime() is returning time
strictly later than its argument.
@pvuorela, I'm sorry for this : / Technically the `.addDays(-1)` will work (that's why tests are passing, including the new ones), but only for recurrence with a period longer or equal to one day…

[mkcal] Correct mistake on starting time for alarm definition.

---

CMakeLists.txt
rpm/mkcal-qt5.spec
src/extendedstorage.cpp
src/extendedstorage.h
src/notebook.cpp
src/notebook.h
src/servicehandler.cpp
src/sqlitestorage.cpp

@pvuorela, this is a selection of commits from #30, commits that don't change the API and may be reviewed independently.
Once we agree on this I'll make another commit with (simple) API break, like:
- remove completely the `isValidNotebook()` as we discussed in #30. It requires a fix in the contact birthday plugin and in the nemo QML calendar plugin, as far as I know.
- change the `deleteNotebook()` API to use a notebook uid and not a notebook pointer.
- change the `defaultNotebook()` and `setDefaultNotebook()` to use uid instead of a notebook pointer.
These API breaks are still less invasive than completely suppressing the ::Ptr part for Notebooks, but they make the ExtendedStorage API simpler and don't require to load Notebook::Ptr from outside mKCal when uids are enough.
What do you …

Protect against notebook storage changes for runtime only notebooks and other clean ups

---

tools/mkcaltool/mkcaltool.cpp

Commit f295c422 introduced a fix for recurring alarms with exceptions. The fix was written in the timed
plugin code to use the full recurring incidence
with exceptions to compute the next alarm occurrence. This code is unit tested, but the place where it is called (the mkcaltool helper) was not updated to
properly load the full incidence description,
including exceptions.
@pvuorela, this is a quick fix for the still existing issue with recurring alarms and exceptions. As mentioned in the commit message, I forgot to properly load the exception defintions from the helper tool that actually set the next alarm on device when discarding the current one.

[mkcal] Fix issue on recurring alarms.

---

src/notebook.cpp

Commit aacdc880b3 moved the uid generation from ExtendedStorage to Notebook. However the default ctor was left not calling the uid generation, thus sync plugins creating plain Notebook instance and then setting the properties was failing.
@Tomin1 @dcaliste

[mkcal] Fix Notebook default ctor not creating a valid notebook. JB#59696

---

src/sqliteformat.cpp
tests/tst_storage.cpp

Setting coordinate implicitly sets this. Also setHasGeo(true) is a no-op on kf5-calendarcore.
@Tomin1 @dcaliste @llewelld

[mkcal] Avoid deprecated Incidence::setHasGeo. Fixes JB#59699

---

src/extendedstorage.cpp
tests/tst_storage.cpp

@pvuorela , yet another alarm issue for recurring events with exceptions. I wrongly assumed that removing an exception in the QML bindings always add an EXDATE for that occurrence. So I initially designed the tests with this assumption in mind in mkcal. But that's not true (anymore?) : for instance, create a recurring event, create an exception by changing the start time for instance on one occurrence, and then delete the exception. The normal occurrence is back, because no EXDATE is set. Delete the normal occurrence and an EXDATE is set.
As you can see from the old test here, the exception deletion and the EXDATE addition was executed at the same time, while if you run the test with two separate actions, and testing the alarm value in-between (as newly implemented), you observe that the …

[mkcal] Reset alarms for recurring events when an exception is removed.

---

rpm/mkcal-qt5.spec
src/sqliteformat.cpp
src/sqliteformat.h
src/sqlitestorage.cpp
tests/tst_storage.cpp
tests/tst_storage.h

@pvuorela: this may become handy if we plan to support changes from a point in time for recurring events at UI level.
There is no test for the migration code path. I run it by hand though on an old database and it seems that the new column is correctly added. And rerunning it on the upgraded database didn't trigger the migration path anymore.

[mkcal] Add DB support for thisAndFuture incidence attribute.

---

src/sqliteformat.cpp
src/sqliteformat.h
src/sqlitestorage.cpp

It's a follow-up of the discussion from #43 .
Trying to make the migration to version with thisAndFuture column, I found that the initial implementation of the thisAndFuture column was wrong. It created different table schema for migrated DB and new DB, thus the INSERT, the UPDATE and the SELECT were wrong, or let say working only in one case... This should be fixed with the first commit, creating the new column always at the end for migrated or new DBs.
Then, as discussed in #43, I try to make the migration steps as atomic as possible, making the write immediate and setting the pragma there, immediately after the DB changes. This is the third commit.
The second commit is a minor simplification when I noticed that the `SL3_exec` macro was filtering out the constraint errors for the sole …

DB migration and thisAndFuture addition

---

CMakeLists.txt
rpm/mkcal-qt5.spec

Otherwise the .pc file is still generated with 0.6.10 as a version and later tests on version in nemo-qml-plugin-calendar for instance are failing…
@pvuorela, if you may review this, please. Thank you.

[mkcal] Bump version in CMakeList so the .pc file is up-to-date.

---

CMakeLists.txt
rpm/mkcal-qt5.spec
src/dummystorage.h
src/extendedstorage.cpp
src/extendedstorage.h
src/sqliteformat.h
src/sqlitestorage.cpp
src/sqlitestorage.h
tests/tst_load.cpp
tests/tst_storage.cpp

@pvuorela, following your advice in #40, I'm proposing this PR where I've deprecated `loadSeries()` and changed the `load()` implementation to act as `loadSeries()`. In addition, I've pushed a commit that always load exceptions (or parents) when using methods that may load one without the other. For instance, if you have attendees in your recurring events, and you setup an exception without attendees, calling `loadByAttendees()` will also load the exception now, ensuring the complete consistency of the event. Of course, it's just database loading, it's then up to the UI not to show the exception in that case.
If this approach is better than the one in #40, I'll close it.

Always load exceptions when loading a recurring event

---

src/extendedcalendar.cpp
src/extendedcalendar.h

Nothing should be needing this, the whole journal support is pretty much unused/untested, and the similar rawEvents() method was removed long time ago already.
Let's just get rid of this one too.
@dcaliste

[mkcal] Remove ExtendedCalendar::rawJournals(). JB#60291

---

src/dummystorage.h
tests/tst_storage.cpp

Apparently the unit test didn't test the compilation good enough in depending projects.
@dcaliste

[mkcal] Add missing mKCal namespace to dummystorage. JB#60291

---

src/sqliteformat.cpp
src/sqliteformat.h
src/sqlitestorage.cpp
tests/tst_storage.cpp

The storage of timezones to check incidences upon
when the incidence timezone name is not matching
any of the system, is deprecated. KCalendarCore
is not providing anymore a timezone definition when parsing ICS data. It is always using the system
timezone definitions to match any received ICS
data. There is thus no need anymore to store a
timezone defintion in the database.
Not to complexify the code, the existing
timezones table is kept as it is, simply not
used anymore.
@pvuorela , let's try this removal also while at it. Tests are still passing, so far so good. The removed part in the observer test is due to the fact that now save() is not emitting updated() all the time. It was the case before because the timezone path was always used and thus the database was always touched. Now it …

[mkcal] Remove timezone from database storage.

---

src/sqliteformat.h
src/sqlitestorage.cpp

Don't reload an existing incidence from DB.
Either the calendar is already in sync with
the calendar or the database has been externally
modified and in that case, the calendar has been
emptied.
Testing the parent incidence in case of recurring
incidence should be enough to guarantee the
existence of all exceptions since the load
methods ensure loading of whole series.
@pvuorela, tests are passing and this PR follow the same spirit as the one introducing the caching for ranges, meaning that there is no point in reloading if we assume that the calendar is in sync with the DB. It is a minor optimisation that should not cost too much in term of maintainablity. It may not be so minor though for search cases where there could be large quantity of events to load by UIDs.

Don't reload event by UID if already in memory.

---

CMakeLists.txt
rpm/mkcal-qt5.spec
src/dummystorage.h
src/extendedstorage.h
src/sqliteformat.h
src/sqlitestorage.cpp
src/sqlitestorage.h
tests/tst_load.cpp

This new method is loading incidences
matching a string pattern in summary, description
or location. Incidences are added to the calendar
and the list of matching instance identifiers is
return to avoid searching in the calendar for match in client code.
@pvuorela, to add search capability to the calendar application, there are two possibilities : either we load all incidences and then search inside the memory calendar for matching incidences, or we delegate the search function to the database and load only matching incidences. The first one does not scale well for large number of incidences. So I went for the second option. But doing so, one needs to know what the database has loaded, to avoid searching again later in the memory calendar. But such information of loaded incidences does …

[mkcal] Add a search method.

---

src/extendedstorage.cpp
tests/tst_storage.cpp

As described in https://forum.sailfishos.org/t/calendar-alarms-dont-work-if-reminder-time-is-in-previous-month-e-g-event-on-april-1-1-00-and-reminder-two-hours-earlier-i-e-on-march-31-23-00/15263/11 , I created a major bug for alarms on recurring events with firing time strictly before the event time.
The bug was in the `addAlarms()` routine in the branch of specific recurring events with a strictly negative alarm offset. It was due to `Recurrence::getNextDateTime()` that returns a date time strictly later than its argument, while I thought it was returning a date time greater or equal than its argument. It was not seen with the tests since I created them for an alarm on the time of the event… My bad, really :/
The fix I'm proposing is a bit simpler than the existing code. Assuming that …

[mkcal] Fix alarm setting for recurring events.

---

src/sqliteformat.cpp
src/sqliteformat.h
src/sqlitestorage.cpp

@pvuorela, this is a proposition not to use ::Ptr internally in SqliteFormat. This is not really mandatory at the moment, nor simplifying much the code, but it helps to disconnect the SQLite backend from a calendar (and also does not pin the incidence ownership to the current thread). Now, SqliteFormat is just taking plain Incidence references to write to the database, or returning new objects on read that the caller is responsible to take ownership of.
It allows to catch some minor issues like changing some internal values of incidence on write, while it should be const.

Remove ::Ptr usage from SqliteFormat

---

src/CMakeLists.txt
src/config-mkcal.h
src/sqliteformat.h

Removed obsolete config-mkcal.h and avoiding installation of the more private headers. And avoid docs for private sqliteformat.h too.
@Tomin1 @dcaliste

Separate private headers

---

CMakeLists.txt
rpm/mkcal-qt5.spec
src/sqlitestorage.cpp
tests/tst_storage.cpp

Like for events, there is no need to ask for
a complete calendar reset on a notebook change
since the modifications are known by the caller.
storageModified should be restricted for out
of process changes.
@pvuorela, since we're at cleaning mKCal API and behaviour, I would like to update the emitted signals on notebook changes. Currently a `storageModified()` signal is emitted, which means for clients "unknown database changes, please reset everything and reload". At first I wanted to create a new signal like the one existing for events (`storageUpdated()`) to notify for the notebook change, but I think there is no need. Clients making notebook changes know the change done since the API is synchronous in contrary to the event one which piles up changes done to the calendar and commit with …

[mkcal] Don't emit storageModified on notebook change.

---

src/CMakeLists.txt
src/alarmhandler.cpp
src/alarmhandler_p.h
src/extendedstorage.cpp

Also change the alarm setting behaviour.
Instead of dealing per incidence, it is
now clearing and setting alarms per UID.
If an incidence recurs and has exceptions,
all alarms sharing the same UID are removed
and then parent and all exceptions are reset.
@pvuorela , yet another spin off from #61.
In the current alarm code, a KCalendarCore::Calendar is required for two things:
- to get the `notebookUid` associated to a given incidence,
- to get the `instances()` list of a recurring incidence, so its next occurrence can be recalculated.
In the context of the coming changes, there won't be necessary a unique KCalendarCore::Calendar that stores the incidences. So I tried to remove it from the alarm API:
- the notebook uid is thus pass in the way of `QPAir<QString, QString>` where the first …

[mkcal] Move alarm handling to a new class.

---

src/extendedcalendar.cpp

Since close() is actually removing the notebook
associations to incidences, and since now mKCal
delete incidences with UID and notebookId, the
current implementation of deleteAllIncidences()
was failing.
@pvuorela and @rainemak, I believe this fix the reported issue of webCAL entries multiplying themselves on sync. The entries were not removed from the database, because the notebook id passed to the SqliteFormat::modifyComponents() was empty, and thus this method was not finding the incidences to delete and considered them already deleted.
@pvuorela, I think the deleteAllIncidences() is only used in the buteo-sync-plugin-webcal. Since, it's a thin wrapper now, one may even remove it from ExtendedCalendar API and put the for loop inside Buteo plugin. What do you think ?

[mkcal] Fix deleteAllIncidences().

---

src/extendedcalendar.cpp
src/extendedcalendar.h
tests/tst_storage.cpp

It is only a thin wrapper around a loop
over all incidences. It can be removed
to avoid confusion on what incidences are
actually deleted and from where.
It also helps to reduce the delta in API
with upstream Calendar class.

[mkcal] Remove deleteAllIncidence() API.

---

rpm/mkcal-qt5.spec
src/invitationhandlerif.h
src/servicehandler.h
src/servicehandlerif.h
src/sqlitestorage.cpp
tests/tests.xml
tests/tst_perf.cpp
tests/tst_storage.cpp
tools/mkcaltool/mkcaltool.cpp

SQLITESTORAGEDB was overly generic when there can be e.g. unit tests that involve multiple databases. Some cleanups while at it.
cc @dcaliste

Support more mkcal specific database override variable
